#!/bin/bash
# Master Pipeline Script
# Running Pretraining then Evaluation sequentially

echo "=== Step 1: BERT SSL Pretraining ==="
python code/01_train_ssl_bert.py

echo "=== Step 2: Comprehensive Evaluation ==="
# Note: Part 3 evaluates on weights/ssl/bert_cutmix_v5_partial.pth by default.
# If you want to use the weights generated by Step 1, update code/03_evaluate_all.py 
# to load 'weights/ssl/bert_standard_ssl_optimized.pth'
python code/03_evaluate_all.py

echo "=== Pipeline Completed ==="
